apiVersion: apps/v1
kind: Deployment
metadata:
  name: dwh-service-deployment
  labels:
    app: dwh-service-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dwh-service-app
  template:
    metadata:
      labels:
        app: dwh-service-app
    spec:
      containers:
      - name: dwh-service-container
        image: europe-central2-docker.pkg.dev/telegrambot-433510/telegram-docker-repo/dwh-service-image:latest
        ports:
        - containerPort: 8080
        env:
        - name: MODE
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: MODE
        - name: DB_DWH_HOST
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: DB_DWH_HOST
        - name: DB_DWH_USER
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: DB_DWH_USER
        - name: DB_DWH_PASS
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: DB_DWH_PASS
        - name: DB_DWH_NAME
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: DB_DWH_NAME
        - name: DB_DWH_PORT
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: DB_DWH_PORT
        - name: MQ_HOST
          valueFrom:
            secretKeyRef:
              name: rabbitmq-secrets
              key: MQ_HOST
        - name: MQ_QUEUE_NAME
          valueFrom:
            secretKeyRef:
              name: rabbitmq-secrets
              key: MQ_QUEUE_NAME
        - name: MQ_QUEUE_USER
          valueFrom:
            secretKeyRef:
              name: rabbitmq-secrets
              key: MQ_QUEUE_USER
        - name: MQ_QUEUE_PASS
          valueFrom:
            secretKeyRef:
              name: rabbitmq-secrets
              key: MQ_QUEUE_PASS
        
