name: Deploy to GKE

on:
  push:
    branches:
      - main  # Trigger on push to the main branch

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT }}
  CLUSTER_NAME: your-cluster-name
  ZONE: us-central1-a  # Set your GKE cluster zone

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
        project_id: ${{ secrets.GCP_PROJECT }}

    - name: Authenticate Docker with GCR
      run: |
        gcloud auth configure-docker

    - name: Build and Push Docker Image
      run: |
        docker build -t gcr.io/${{ secrets.GCP_PROJECT }}/your-image:latest .
        docker push gcr.io/${{ secrets.GCP_PROJECT }}/your-image:latest

    - name: Get GKE credentials
      run: |
        gcloud container clusters get-credentials $CLUSTER_NAME --zone $ZONE --project $PROJECT_ID

    - name: Deploy to GKE
      run: |
        kubectl apply -f k8s/deployment.yaml
        kubectl apply -f k8s/service.yaml
        kubectl apply -f k8s/secrets.yaml
